build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

API Tests:
  stage: test
  image: node:18.16.0-alpine
  script:
    - echo "This job tests APIs"
    - npm install --global mocha
    - npm run test


deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
