UI Tests:
  stage: test
  image: node:18.16.0-alpine
  before_script:
    - apk add --no-cache sudo curl build-base g++ libpng libpng-dev jpeg-dev pango-dev cairo-dev giflib-dev python3 firefox xvfb chromium chromium-chromedriver
    - export DISPLAY=:99
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  script: 
    - export DISPLAY=:99
    - npm install --save-dev @wdio/local-runner
    - npm install -global wdio @wdio/cli cucumber  geckodriver
    - npm run wdio
  artifacts:
    when: always
    paths:
      - ./report
    reports: 
      junit: ./report/results.xml
    expire_in: 1 week
