build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

Unit Tests:
  stage: test
  script:
    - echo "This job tests something"

UI Tests:
stages: 
  - test 
image: node:18.16.0-alpine 
before_script: 
  - apk add --no-cache sudo curl build-base g++ libpng libpng-dev jpeg-dev pango-dev cairo-dev giflib-dev python3 firefox

BDD Tests:
stage: test
script: 
  - echo "This job BDD Tests"


deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
