Unit Tests:
  stage: test
  image: node:18.16.0-alpine
  script:
    - echo "This job tests APIs"
    - npm install -global mocha c8 mochawesome prettier
    - npm install chai # Add this line to install chai
    - npm run test
